<?php

/* * *******************************************************************************
 * The content of this file is subject to the MYC Vtiger Customer Portal license.
 * ("License"); You may not use this file except in compliance with the License
 * The Initial Developer of the Original Code is Proseguo s.l. - MakeYourCloud
 * Portions created by Proseguo s.l. - MakeYourCloud are Copyright(C) Proseguo s.l. - MakeYourCloud
 * All Rights Reserved.
 * ****************************************************************************** */

return array(
	"Pacific/Enderbury" => "(GMT+13:00) Phoenix Islands Time ( Pacific / Enderbury  )",
	"Pacific/Tongatapu" => "(GMT+13:00) Tonga Time ( Pacific / Tongatapu )",
	"Pacific/Chatham" => "(GMT+12:45) Chatham Standard Time ( Pacific / Chatham )",
	"Asia/Kamchatka" => "(GMT+12:00) Magadan Time ( Asia / Kamchatka )",
	"Pacific/Auckland" => "(GMT+12:00) New Zealand Standard Time ( Pacific / Auckland )",
	"Pacific/Fiji" => "(GMT+12:00) Fiji Time ( Pacific / Fiji )",
	"Pacific/Norfolk" => "(GMT+11:30) Norfolk Islands Time ( Pacific / Norfolk )",
	"Pacific/Guadalcanal" => "(GMT+11:00) Solomon Islands Time ( Pacific / Guadalcanal )",
	"Australia/Lord_Howe" => "(GMT+10:30) Lord Howe Standard Time ( Australia / Lord_Howe )",
	"Australia/Brisbane" => "(GMT+10:00) Australian Eastern Standard Time ( Australia / Brisbane )",
	"Australia/Sydney" => "(GMT+10:00) Australian Eastern Standard Time ( Australia / Sydney )",
	"Australia/Adelaide" => "(GMT+09:30) Australian Central Standard Time ( Australia / Adelaide )",
	"Australia/Darwin" => "(GMT+09:30) Australian Central Standard Time ( Australia / Darwin )",
	"Asia/Seoul" => "(GMT+09:00) Korean Standard Time ( Asia / Seoul )",
	"Asia/Tokyo" => "(GMT+09:00) Japan Standard Time ( Asia / Tokyo )",
	"Asia/Hong_Kong" => "(GMT+08:00) Hong Kong Time ( Asia / Hong_Kong )",
	"Asia/Kuala_Lumpur" => "(GMT+08:00) Malaysia Time ( Asia / Kuala_Lumpur )",
	"Asia/Manila" => "(GMT+08:00) Philippine Time ( Asia / Manila )",
	"Asia/Shanghai" => "(GMT+08:00) China Standard Time ( Asia / Shanghai )",
	"Asia/Singapore" => "(GMT+08:00) Singapore Standard Time ( Asia / Singapore )",
	"Asia/Taipei" => "(GMT+08:00) Taipei Standard Time ( Asia / Taipei )",
	"Australia/Perth" => "(GMT+08:00) Australian Western Standard Time ( Australia / Perth )",
	"Asia/Bangkok" => "(GMT+07:00) Indochina Time ( Asia / Bangkok )",
	"Asia/Jakarta" => "(GMT+07:00) Western Indonesia Time ( Asia / Jakarta )",
	"Asia/Saigon" => "(GMT+07:00) Indochina Time ( Asia / Saigon )",
	"Asia/Rangoon" => "(GMT+06:30) Myanmar Time ( Asia / Rangoon )",
	"Asia/Dacca" => "(GMT+06:00) Bangladesh Time ( Asia / Dacca )",
	"Asia/Yekaterinburg" => "(GMT+06:00) Yekaterinburg Time ( Asia / Yekaterinburg )",
	"Asia/Katmandu" => "(GMT+05:45) Nepal Time ( Asia / Katmandu )",
	"Asia/Calcutta" => "(GMT+05:30) India Standard Time ( Asia / Calcutta )",
	"Asia/Colombo" => "(GMT+05:30) India Standard Time ( Asia / Colombo )",
	"Asia/Baku" => "(GMT+05:00) Azerbaijan Summer Time ( Asia / Baku )",
	"Asia/Karachi" => "(GMT+05:00) Pakistan Time ( Asia / Karachi )",
	"Asia/Tashkent" => "(GMT+05:00) Uzbekistan Time ( Asia / Tashkent )",
	"Asia/Kabul" => "(GMT+04:30) Afghanistan Time ( Asia / Kabul )",
	"Asia/Tehran" => "(GMT+04:30) Iran Daylight Time ( Asia / Tehran )",
	"Asia/Dubai" => "(GMT+04:00) Gulf Standard Time ( Asia / Dubai )",
	"Asia/Tbilisi" => "(GMT+04:00) Georgia Time ( Asia / Tbilisi )",
	"Asia/Yerevan" => "(GMT+04:00) Armenia Time ( Asia / Yerevan )",
	"Europe/Moscow" => "(GMT+04:00) Moscow Standard Time ( Europe / Moscow )",
	"Africa/Nairobi" => "(GMT+03:00) East Africa Time ( Africa / Nairobi )",
	"Asia/Baghdad" => "(GMT+03:00) Arabian Standard Time ( Asia / Baghdad )",
	"Asia/Beirut" => "(GMT+03:00) Eastern European Summer Time ( Asia / Beirut )",
	"Asia/Jerusalem" => "(GMT+03:00) Israel Daylight Time ( Asia / Jerusalem )",
	"Asia/Kuwait" => "(GMT+03:00) Arabian Standard Time ( Asia / Kuwait )",
	"Asia/Riyadh" => "(GMT+03:00) Arabian Standard Time ( Asia / Riyadh )",
	"Europe/Athens" => "(GMT+03:00) Eastern European Summer Time ( Europe / Athens )",
	"Europe/Bucharest" => "(GMT+03:00) Eastern European Summer Time ( Europe / Bucharest )",
	"Europe/Helsinki" => "(GMT+03:00) Eastern European Summer Time ( Europe / Helsinki )",
	"Europe/Istanbul" => "(GMT+03:00) Eastern European Summer Time ( Europe / Istanbul )",
	"Europe/Minsk" => "(GMT+03:00) Further-Eastern European Time ( Europe / Minsk )",
	"Africa/Cairo" => "(GMT+02:00) Eastern European Time ( Africa / Cairo )",
	"Africa/Johannesburg" => "(GMT+02:00) South Africa Standard Time ( Africa / Johannesburg )",
	"Europe/Amsterdam" => "(GMT+02:00) Central European Summer Time ( Europe / Amsterdam )",
	"Europe/Berlin" => "(GMT+02:00) Central European Summer Time ( Europe / Berlin )",
	"Europe/Brussels" => "(GMT+02:00) Central European Summer Time ( Europe / Brussels )",
	"Europe/Paris" => "(GMT+02:00) Central European Summer Time ( Europe / Paris )",
	"Europe/Prague" => "(GMT+02:00) Central European Summer Time ( Europe / Prague )",
	"Europe/Rome" => "(GMT+02:00) Central European Summer Time ( Europe / Rome )",
	"Africa/Algiers" => "(GMT+01:00) Central European Time ( Africa / Algiers )",
	"Africa/Casablanca" => "(GMT+01:00) Western European Summer Time ( Africa / Casablanca )",
	"Europe/Dublin" => "(GMT+01:00) Irish Summer Time ( Europe / Dublin )",
	"Europe/Lisbon" => "(GMT+01:00) Western European Summer Time ( Europe / Lisbon )",
	"Europe/London" => "(GMT+01:00) British Summer Time ( Europe / London )",
	"America/Scoresbysund" => "(GMT+00:00) East Greenland Summer Time ( America / Scoresbysund )",
	"Atlantic/Azores" => "(GMT+00:00) Azores Summer Time ( Atlantic / Azores )",
	"GMT" => "(GMT+00:00) Greenwich Mean Time ( GMT )",
	"Atlantic/Cape_Verde" => "(GMT-01:00) Cape Verde Time ( Atlantic / Cape_Verde )",
	"Atlantic/South_Georgia" => "(GMT-02:00) South Georgia Time ( Atlantic / South_Georgia )",
	"America/St_Johns" => "(GMT-02:30) Newfoundland Daylight Time ( America / St_Johns )",
	"America/Buenos_Aires" => "(GMT-03:00) Argentina Time ( America / Buenos_Aires )",
	"America/Halifax" => "(GMT-03:00) Atlantic Daylight Time ( America / Halifax )",
	"America/Sao_Paulo" => "(GMT-03:00) Brasilia Time ( America / Sao_Paulo )",
	"Atlantic/Bermuda" => "(GMT-03:00) Atlantic Daylight Time ( Atlantic / Bermuda )",
	"America/Indianapolis" => "(GMT-04:00) Eastern Daylight Time ( America / Indianapolis )",
	"America/New_York" => "(GMT-04:00) Eastern Daylight Time ( America / New_York )",
	"America/Puerto_Rico" => "(GMT-04:00) Atlantic Standard Time ( America / Puerto_Rico )",
	"America/Santiago" => "(GMT-04:00) Chile Time ( America / Santiago )",
	"America/Caracas" => "(GMT-04:30) Venezuela Time ( America / Caracas )",
	"America/Bogota" => "(GMT-05:00) Colombia Time ( America / Bogota )",
	"America/Chicago" => "(GMT-05:00) Central Daylight Time ( America / Chicago )",
	"America/Lima" => "(GMT-05:00) Peru Time ( America / Lima )",
	"America/Mexico_City" => "(GMT-05:00) Central Daylight Time ( America / Mexico_City )",
	"America/Panama" => "(GMT-05:00) Eastern Standard Time ( America / Panama )",
	"America/Denver" => "(GMT-06:00) Mountain Daylight Time ( America / Denver )",
	"America/El_Salvador" => "(GMT-06:00) Central Standard Time ( America / El_Salvador )",
	"Mexico/BajaSur" => "(GMT-06:00) Mountain Daylight Time ( Mexico / BajaSur )",
	"America/Los_Angeles" => "(GMT-07:00) Pacific Daylight Time ( America / Los_Angeles )",
	"America/Phoenix" => "(GMT-07:00) Mountain Standard Time ( America / Phoenix )",
	"America/Tijuana" => "(GMT-07:00) Pacific Daylight Time ( America / Tijuana )",
	"America/Anchorage" => "(GMT-08:00) Alaska Daylight Time ( America / Anchorage )",
	"Pacific/Pitcairn" => "(GMT-08:00) Pitcairn Time ( Pacific/Pitcairn )",
	"America/Atka" => "(GMT-09:00) Hawaii-Aleutian Standard Time ( America / Atka )",
	"Pacific/Gambier" => "(GMT-09:00) Gambier Time ( Pacific / Gambier )",
	"Pacific/Marquesas" => "(GMT-09:30) Marquesas Time ( Pacific / Marquesas )",
	"Pacific/Honolulu" => "(GMT-10:00) Hawaii-Aleutian Standard Time ( Pacific / Honolulu )",
	"Pacific/Niue" => "(GMT-11:00) Niue Time ( Pacific / Niue )",
	"Pacific/Pago_Pago" => "(GMT-11:00) Samoa Standard Time ( Pacific / Pago_Pago )",
);